name: Schedule Lightning Data Script
on:
  schedule:
    # Cron job format: 'minute hour day month weekday'
    # This cron runs daily at 2:00 AM UTC
    - cron: '0 2 * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can use another version if needed
    - name: Install dependencies
      run: |
        pip install requests pandas  # Install dependencies
    - name: Run lightning script
      run: |
        python ls.py  # Run the script
    - name: Git status check
      run: git status
    
    - name: Commit and push changes
      run: |
        git config --global user.name "kevwee-lab"
        git config --global user.email "kevwee-lab@users.noreply.github.com"
    
        git add lightning_data.csv
    
        git status  # Show what's staged
    
        # If nothing is staged, skip commit
        git diff --cached --quiet && echo "No changes to commit" && exit 0
    
        git commit -m "Updated lightning data"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.ref }}
