name: Lightning Data Collector
on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install requests pandas

    - name: Create data directory
      run: mkdir -p lightning_data  # Always succeeds

    - name: Run script
      run: python ls.py  # Your Python code handles the rest

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Safe add command (works with 0 files)
        git add lightning_data/ || echo "No files to add"
        
        # Commit only if changes exist
        if ! git diff --cached --quiet; then
          git commit -m "Automatic lightning data update"
          git push
        else
          echo "No changes to commit"
        fi
